### ISSUE TITLE
What may happened with buffer's range error?

### ISSUE THREAD

**Issue by mike442144** [veny/GearmaNode#38]
buffer.js:506
    throw new RangeError('index out of range');
    ^
RangeError: index out of range
    at checkOffset (buffer.js:506:11)
    at Buffer.readUInt32BE (buffer.js:580:5)
    at JobServer._processData (/root/sp/node_modules/gearmanode/lib/gearmanode/job-server.js:278:15)
    at Socket.<anonymous> (/root/sp/node_modules/gearmanode/lib/gearmanode/job-server.js:129:18)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by mike442144** [comment]
This happened over and over, all my program crashed, Is it a bug?

**Comment by mike442144** [comment]
blew is stack info:
RangeError: index out of range
at checkOffset (buffer.js:506:11)
at Buffer.readUInt32BE (buffer.js:580:5)
at JobServer._processData (/root/sp/node_modules/gearmanode/lib/gearmanode/job-server.js:278:15)
at Socket.<anonymous> (/root/sp/node_modules/gearmanode/lib/gearmanode/job-server.js:129:18)

then got this error:
out of sync with server

**Comment by veny** [comment]
please try the last version

**Comment by mike442144** [comment]
It's a problem while handling TCP packet which is fixed in last version by my colleague.
