### ISSUE TITLE
Getting "Error: out of sync with server" when multiple packets returned from gearman server

### ISSUE THREAD

**Issue by fillmorejd** [veny/GearmaNode#6]
I'm returning a large JSON data set from gearman and it is split into two packets. 
verbose: received packet, len=1448
verbose: received packet, len=1669

the second packet always causes an "Error: out of sync with server" because it doesn't have the leading data for the packet type.

The two packets are never combined so the data is always incomplete.

Any idea how we can update the code to work with multiple packets of data?

**Comment by zero0707** [comment]
I encounter a similar problem。
I just run worker and client on one machine, and for some time , it show the message as follows.
what reason can cause it? 
thank you.

error:  Error: out of sync with server
    at Client._unrecoverableError (/home/zero/Projects/spider/node_modules/gearmanode/lib/gearmanode/client.js:280:24)
    at JobServer._processData (/home/zero/Projects/spider/node_modules/gearmanode/lib/gearmanode/job-server.js:281:33)
    at Socket.<anonymous> (/home/zero/Projects/spider/node_modules/gearmanode/lib/gearmanode/job-server.js:129:18)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
